import { AppThemeConfig } from "../types";

export const THEMES: AppThemeConfig[] = [
  {
    id: "emerald",
    name: "Cyber Emerald",
    primary: "text-emerald-400",
    primaryBg: "bg-emerald-500/10",
    primaryBorder: "border-emerald-500/20",
    accentColor: "#10b981",
    glowShadow: "shadow-emerald-500/20",
    gradient: "from-emerald-400 to-teal-500",
  },
  {
    id: "ruby",
    name: "Neon Ruby",
    primary: "text-rose-400",
    primaryBg: "bg-rose-500/10",
    primaryBorder: "border-rose-500/20",
    accentColor: "#f43f5e",
    glowShadow: "shadow-rose-500/20",
    gradient: "from-rose-500 to-orange-400",
  },
  {
    id: "cyan",
    name: "Future Cyan",
    primary: "text-cyan-400",
    primaryBg: "bg-cyan-500/10",
    primaryBorder: "border-cyan-500/20",
    accentColor: "#06b6d4",
    glowShadow: "shadow-cyan-500/20",
    gradient: "from-cyan-400 to-blue-500",
  },
  {
    id: "indigo",
    name: "Cosmic Indigo",
    primary: "text-indigo-400",
    primaryBg: "bg-indigo-500/10",
    primaryBorder: "border-indigo-500/20",
    accentColor: "#6366f1",
    glowShadow: "shadow-indigo-500/20",
    gradient: "from-indigo-400 to-purple-500",
  },
  {
    id: "amber",
    name: "Retro Amber",
    primary: "text-amber-400",
    primaryBg: "bg-amber-500/10",
    primaryBorder: "border-amber-500/20",
    accentColor: "#f59e0b",
    glowShadow: "shadow-amber-500/20",
    gradient: "from-amber-400 to-yellow-500",
  },
  {
    id: "rose",
    name: "Sakura Velvet",
    primary: "text-fuchsia-400",
    primaryBg: "bg-fuchsia-500/10",
    primaryBorder: "border-fuchsia-500/20",
    accentColor: "#e879f9",
    glowShadow: "shadow-fuchsia-500/20",
    gradient: "from-fuchsia-400 to-pink-500",
  }
];
